
public enum Subject {
	CS, CIS, MATH, STAT,
	// GENEDS :(
	BUS, ISAT, SMAD, PHIL, SCOM, WRTC, ASTR, CHEM, ISCI, PHYS, BIO, ANTH, GEOL, PSYC, AMST, HIST, HUM, REL, ART, ARTH,
	MUS, TEHA, ENG, JUST, POSC, AAAD, ECON, GEOG, SOCI, HTH, KIN, WGSS, THEA

}
